BEGIN;

-- 1. Arrumar a tabela COMPANIES primeiro (Renomear client_seq_id para id e torná-lo Primary Key)
DO $$ 
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='companies' AND column_name='client_seq_id') THEN
        -- Remove resquícios da PK antiga se existir
        ALTER TABLE public.companies DROP CONSTRAINT IF EXISTS companies_pkey CASCADE;
        -- Renomeia
        ALTER TABLE public.companies RENAME COLUMN client_seq_id TO id;
        -- Força a PK
        ALTER TABLE public.companies ADD PRIMARY KEY (id);
    END IF;
END $$;

-- 2. Garantir que a tabela COMPANIES tenha o auto-incremento (Identity) no `id`
DO $$ 
DECLARE
    max_id int;
BEGIN
    -- Isso garante que novos cadastros funcionem 1, 2, 3...
    EXECUTE 'SELECT COALESCE(MAX(id), 0) + 1 FROM public.companies' INTO max_id;
    BEGIN
        EXECUTE format('ALTER TABLE public.companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)', max_id);
    EXCEPTION WHEN others THEN
        -- ignora se já for identity
    END;
END $$;

-- 3. Limpar a bagunça nas tabelas filhas (Remover UUIDs quebrados e constraints)
DO $$ 
DECLARE
    t text;
    tables text[] := ARRAY['movements', 'financial_entries', 'inventory', 'sales', 'partners', 'documents', 'profiles'];
BEGIN
    FOREACH t IN ARRAY tables LOOP
        -- Tira a foreign key velha se existir
        BEGIN EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT IF EXISTS %I_company_id_fkey', t, t); EXCEPTION WHEN others THEN null; END;
        
        -- Verificar se a 'company_id' atual é uma string ou UUID (tipo antigo)
        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name=t AND column_name='company_id' AND data_type IN ('character varying', 'uuid', 'text')) THEN
            -- Aborta a coluna de texto pra sempre
            EXECUTE format('ALTER TABLE public.%I DROP COLUMN company_id CASCADE', t);
        END IF;
    END LOOP;
END $$;

-- 4. Renomear new_company_id (se deu tempo de gerar na primeira tentativa) para company_id, ou recriar a coluna como Integer
DO $$ 
DECLARE
    t text;
    tables text[] := ARRAY['movements', 'financial_entries', 'inventory', 'sales', 'partners', 'documents', 'profiles'];
BEGIN
    FOREACH t IN ARRAY tables LOOP
        -- Se existe new_company_id, significa que dados conseguiram ser salvos ali, então apenas renomeamos
        IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name=t AND column_name='new_company_id') THEN
            EXECUTE format('ALTER TABLE public.%I RENAME COLUMN new_company_id TO company_id', t);
        ELSE
            -- Se não existe 'new_company_id' e não existe a 'company_id' que acabamos de dropar, cria uma INT em branco.
            IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name=t AND column_name='company_id') THEN
                EXECUTE format('ALTER TABLE public.%I ADD COLUMN company_id int4', t);
            END IF;
        END IF;
    END LOOP;
END $$;

-- 5. Recriar (ou forçar) todas as Foreign Keys para o novo 'id' Integer da companies
DO $$ 
DECLARE
    t text;
    tables text[] := ARRAY['movements', 'financial_entries', 'inventory', 'sales', 'partners', 'documents', 'profiles'];
BEGIN
    FOREACH t IN ARRAY tables LOOP
        BEGIN 
            EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE', t, t); 
        EXCEPTION WHEN duplicate_object THEN 
            null; 
        END;
    END LOOP;
END $$;

COMMIT;
